# Generated by Django 4.0 on 2022-01-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('pasword', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField()),
                ('account_type', models.CharField(max_length=200)),
            ],
        ),
    ]
