# Generated by Django 4.0 on 2022-01-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
            ],
        ),
    ]
