# Generated by Django 4.0 on 2022-01-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0002_ref_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='ref_links',
            name='email',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ref_links',
            name='password',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
