# Generated by Django 3.2.11 on 2022-02-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0003_ref_links_email_ref_links_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
    ]
