# Generated by Django 3.2.11 on 2022-02-25 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0004_updates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Updates',
        ),
    ]
